// Generated by Wrangler on Mon Jun 03 2024 10:24:45 GMT-0500 (Central Daylight Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	OPENAI_API_KEY: string;
	CLOUDFLARE_ACCOUNT_ID: string;
	AI: Ai;
}
